pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
        IMAGE_NAME = 'yourdockerhubusername/jen_project1'
    }

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/cnitika/jen_Project1.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Login to DockerHub') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push $IMAGE_NAME'
            }
        }

        stage('Deploy Locally') {
            steps {
                sh 'docker rm -f flaskapp || true'
                sh 'docker run -d -p 5000:5000 --name flaskapp $IMAGE_NAME'
            }
        }
    }
}
